#K8s Deployment Pipeline
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

variables:
  ARM_CLIENT_ID: $(servicePrincipalId)
  ARM_CLIENT_SECRET: $(servicePrincipalKey)
  ARM_SUBSCRIPTION_ID: $(subscriptionId)
  ARM_TENANT_ID: $(tenantId)

steps:
- script: |
    echo "Logging into Azure..."
    az login --service-principal -u $(ARM_CLIENT_ID) -p $(ARM_CLIENT_SECRET) --tenant $(ARM_TENANT_ID)

    echo "Setting subscription..."
    az account set --subscription $(ARM_SUBSCRIPTION_ID)

    echo "Installing Terraform..."
    curl -s https://raw.githubusercontent.com/hashicorp/terraform-installer/master/install.sh | bash

    echo "Initializing Terraform..."
    terraform init

    echo "Planning infrastructure changes..."
    terraform plan

    echo "Applying infrastructure changes..."
    terraform apply -auto-approve
  displayName: "Run Azure CLI and Terraform"
